AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: news
      AttributeDefinitions:
        - AttributeName: sentiment
          AttributeType: S
        - AttributeName: timestamp
          AttributeType: S
      KeySchema:
        - AttributeName: sentiment
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE